anchor_version = "0.28.0"

[workspace]
members = ["programs/farming"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
farming = "kJsQ8P7cKZneV3tTQPGP8xKz5mpMxrgDatWNQRiYmvG"


